In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(1)

In [3]:
x_train = torch.FloatTensor([[1], [2], [3]]) #훈련 데이터
y_train = torch.FloatTensor([[2], [4], [6]])

In [4]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True)
# 가중치 W를 출력
print(W)

tensor([0.], requires_grad=True)


In [5]:
b = torch.zeros(1, requires_grad=True) #bias도 변경됨
print(b)

tensor([0.], requires_grad=True)


In [6]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [7]:
# 앞서 배운 torch.mean으로 평균을 구한다. Cost funciton
cost = torch.mean((hypothesis - y_train) ** 2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [8]:
optimizer = optim.SGD([W, b], lr=0.01)
# 학습 대상인 W와 b가 SGD의 입력이 됨.

In [9]:
optimizer.zero_grad()
cost.backward()
optimizer.step()
#하강법 최적화 함수 opimizer의 .step() 함수를 호출하여
#인수로 들어갔던 W와 b에서 리턴되는 변수들의 기울기에 학습률(learining rate) 0.01을
#곱하여 빼줌으로서 업데이트합니다.

In [11]:
num_epochs = 1999
for epoch in range(num_epochs + 1):
  # H(x) 계산
  hypothesis = x_train * W + b

  # cost 계산
  cost = torch.mean((hypothesis - y_train) ** 2)

  # cost로 H(x) 개선
  optimizer.zero_grad() # 미분을 통해 얻은 기울기를 0으로 초기화합니다.
  cost.backward() # 비용 함수를 미분하여 gradient 계산
  optimizer.step() #위 backward를 통해 x - x*lr 로 경사하강법 실행
  #경사 하강법은 비용 함수를 미분하여 이 함수의 기울기(gradient)를 구해서 비용이 최소화 되는 방향을 찾아내는 알고리즘

  # 100번마다 로그 출력
  if epoch % 100 == 0:
      print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
          epoch, num_epochs, W.item(), b.item(), cost.item()
      ))

Epoch    0/1999 W: 0.353, b: 0.151 Cost: 14.770963
Epoch  100/1999 W: 1.746, b: 0.577 Cost: 0.047939
Epoch  200/1999 W: 1.801, b: 0.453 Cost: 0.029624
Epoch  300/1999 W: 1.843, b: 0.356 Cost: 0.018306
Epoch  400/1999 W: 1.877, b: 0.280 Cost: 0.011312
Epoch  500/1999 W: 1.903, b: 0.220 Cost: 0.006990
Epoch  600/1999 W: 1.924, b: 0.173 Cost: 0.004319
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002669
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001649
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001019
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000630
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000389
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000240
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

optimizer.zero_grad()가 필요한 이유 : 파이토치는 미분을 통해 얻은 기울기를 이전에 계산된 기울기 값에 누적시키는 특징이 있습니다.

그렇기 때문에 optimizer.zero_grad()를 통해 미분값을 계속 0으로 초기화시켜줘야 합니다.



In [12]:
import torch
w = torch.tensor(2.0, requires_grad=True)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

  z = 2*w

  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0


torch.manual_seed()를 하는 이유 : torch.manual_seed()를 사용한 프로그램의 결과는 다른 컴퓨터에서 실행시켜도 동일한 결과를 얻을 수 있습니다.

그 이유는 torch.manual_seed()는 난수 발생 순서와 값을 동일하게 보장해준다는 특징때문입니다.

우선 랜덤 시드가 3일 때 두 번 난수를 발생시켜보고, 다른 랜덤 시드를 사용한 후에 다시 랜덤 시드를 3을 사용한다면 난수 발생값이 동일하게 나오는지 보겠습니다.

In [13]:
import torch
torch.manual_seed(3)
print('랜덤 시드가 3일 때')
for i in range(1,3):
  print(torch.rand(1))

랜덤 시드가 3일 때
tensor([0.0043])
tensor([0.1056])


In [14]:
torch.manual_seed(5)
print('랜덤 시드가 5일 때')
for i in range(1,3):
  print(torch.rand(1))

랜덤 시드가 5일 때
tensor([0.8303])
tensor([0.1261])


In [15]:
torch.manual_seed(3)
print('랜덤 시드가 다시 3일 때')
for i in range(1,3):
  print(torch.rand(1))

랜덤 시드가 다시 3일 때
tensor([0.0043])
tensor([0.1056])


텐서에는 requires_grad라는 속성이 있습니다. 이것을 True로 설정하면 자동 미분 기능이 적용됩니다.

선형 회귀부터 신경망과 같은 복잡한 구조에서 파라미터들이 모두 이 기능이 적용됩니다.

requires_grad = True가 적용된 텐서에 연산을 하면, 계산 그래프가 생성되며 backward 함수를 호출하면 그래프로부터 자동으로 미분이 계산됩니다.

파이토치의 학습 과정을 보다 더 잘 이해하기 위해서 자동 미분에 대해서 이해해봅시다.

In [16]:
import torch


w = torch.tensor(2.0, requires_grad=True)


y = w**2
z = 2*y + 5


z.backward()


print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


# Multivariable Linear regression

In [17]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [18]:
# 훈련 데이터
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [19]:
# 가중치 w와 편향 b 초기화
w1 = torch.zeros(1, requires_grad=True)
w2 = torch.zeros(1, requires_grad=True)
w3 = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [20]:
# optimizer 설정
optimizer = optim.SGD([w1, w2, w3, b], lr=1e-5)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))


Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


## 벡터와 행렬 연산으로 바꾸기

In [21]:
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  80],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [22]:
w = torch.zeros((3,1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [23]:
hypothesis = x_train.matmul(w) + b


optimizer = optim.SGD([w, b], lr=1e-5)


In [24]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(w) + b #행렬 곱

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

In [29]:
# 임의의 입력 값에 대한 예측
with torch.no_grad():
    new_input = torch.FloatTensor([[75, 85, 72]])  # 예측하고 싶은 임의의 입력
    prediction = new_input.matmul(w) + b
    print('Predicted value for input {}: {}'.format(new_input.squeeze().tolist(), prediction.item()))

Predicted value for input [75.0, 85.0, 72.0]: 156.8051300048828


## nn.Module로 구현하는 선형 회귀

In [30]:
import torch
import torch.nn as nn
import torch.nn.functional as F


torch.manual_seed(1)

x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[2],[4],[6]])


model = nn.Linear(1,1)

print(list(model.parameters()))
# 첫번째 값이 W / 두번째 값이 b => 두 값모두 랜덤으로 초기화 되어있음.

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [31]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)


num_epochs = 2000
for epoch in range(num_epochs+1):
  pred = model(x_train)
  cost =F.mse_loss(pred, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, num_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [32]:
# 임의의 입력 4를 선언
new_var =  torch.FloatTensor([[4.0]])
# 입력한 값 4에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) # forward 연산
# y = 2x 이므로 입력이 4라면 y가 8에 가까운 값이 나와야 제대로 학습이 된 것
print("훈련 후 입력이 4일 때의 예측값 :", pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward0>)


4일 때 7.9989 -> 8 예측

w,b 출력

In [33]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


x에서 y 예측하는 것 :  forward 연산이라고 합니다.

학습 전, prediction = model(x_train)은 x_train으로부터 예측값을 리턴하므로 forward 연산입니다.

학습 후, pred_y = model(new_var)는 임의의 값 new_var로부터 예측값을 리턴하므로 forward 연산입니다.

학습 과정에서 비용 함수를 미분하여 기울기를 구하는 것을 backward 연산이라고 합니다.

cost.backward()는 비용 함수로부터 기울기를 구하라는 의미이며 backward 연산입니다.

## 다중 선형 회귀 구현

In [34]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [35]:
model = nn.Linear(3,1)


print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [36]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [38]:
nb_epochs = 20000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)
    # model(x_train)은 model.forward(x_train)와 동일함.

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward()
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))


Epoch    0/20000 Cost: 2.237009
Epoch  100/20000 Cost: 2.127978
Epoch  200/20000 Cost: 2.024705
Epoch  300/20000 Cost: 1.926857
Epoch  400/20000 Cost: 1.834178
Epoch  500/20000 Cost: 1.746393
Epoch  600/20000 Cost: 1.663238
Epoch  700/20000 Cost: 1.584445
Epoch  800/20000 Cost: 1.509820
Epoch  900/20000 Cost: 1.439145
Epoch 1000/20000 Cost: 1.372169
Epoch 1100/20000 Cost: 1.308725
Epoch 1200/20000 Cost: 1.248645
Epoch 1300/20000 Cost: 1.191720
Epoch 1400/20000 Cost: 1.137781
Epoch 1500/20000 Cost: 1.086708
Epoch 1600/20000 Cost: 1.038323
Epoch 1700/20000 Cost: 0.992460
Epoch 1800/20000 Cost: 0.949036
Epoch 1900/20000 Cost: 0.907903
Epoch 2000/20000 Cost: 0.868927
Epoch 2100/20000 Cost: 0.832009
Epoch 2200/20000 Cost: 0.797045
Epoch 2300/20000 Cost: 0.763909
Epoch 2400/20000 Cost: 0.732521
Epoch 2500/20000 Cost: 0.702791
Epoch 2600/20000 Cost: 0.674617
Epoch 2700/20000 Cost: 0.647933
Epoch 2800/20000 Cost: 0.622657
Epoch 2900/20000 Cost: 0.598701
Epoch 3000/20000 Cost: 0.576008
Epoch 31

In [39]:
new_var =  torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[151.6222]], grad_fn=<AddmmBackward0>)


In [40]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.0707, 0.5358, 0.4032]], requires_grad=True), Parameter containing:
tensor([0.3596], requires_grad=True)]


## 모델을 클래스로 구현하기

### Linear Regression

In [41]:
class LinearRegressionModel(nn.Module):
  def __init__(self): # init에서 모델의 구조와 동적을 정의하는 생성자를 정의
    super().__init__() # nn.Module의 속성을 갖게 됨
    self.linear = nn.Linear(1, 1)

  def forward(self, x): # model객체를 데이터와 함께 호출하면 자동으로 실행 됨
    return self.linear(x)

In [42]:
model = LinearRegressionModel()

In [43]:
model

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

### Multi-Variable Linear Regression

In [44]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)

In [45]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)


In [46]:
model = MultivariateLinearRegressionModel()


In [47]:
model

MultivariateLinearRegressionModel(
  (linear): Linear(in_features=3, out_features=1, bias=True)
)

In [48]:
torch.manual_seed(1)

In [50]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [51]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 다중 선형 회귀이므로 input_dim=3, output_dim=1.

    def forward(self, x):
        return self.linear(x)

In [52]:
model = MultivariateLinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr=1e-5)


num_epochs = 2000
for epoch in range(num_epochs + 1):
  pred = model(x_train)
  cost = F.mse_loss(pred, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    print("Epoch {:4d}/{} Cost:{:6f}".format(epoch, num_epochs, cost.item()))

Epoch    0/2000 Cost:31667.597656
Epoch  100/2000 Cost:0.225993
Epoch  200/2000 Cost:0.223911
Epoch  300/2000 Cost:0.221941
Epoch  400/2000 Cost:0.220059
Epoch  500/2000 Cost:0.218271
Epoch  600/2000 Cost:0.216575
Epoch  700/2000 Cost:0.214950
Epoch  800/2000 Cost:0.213413
Epoch  900/2000 Cost:0.211952
Epoch 1000/2000 Cost:0.210560
Epoch 1100/2000 Cost:0.209232
Epoch 1200/2000 Cost:0.207967
Epoch 1300/2000 Cost:0.206761
Epoch 1400/2000 Cost:0.205619
Epoch 1500/2000 Cost:0.204522
Epoch 1600/2000 Cost:0.203484
Epoch 1700/2000 Cost:0.202485
Epoch 1800/2000 Cost:0.201542
Epoch 1900/2000 Cost:0.200635
Epoch 2000/2000 Cost:0.199769


# Mini Batch and DataLoader

![](https://wikidocs.net/images/page/36033/batchandepochiteration.PNG)

In [53]:
from torch.utils.data import TensorDataset # 텐서데이터셋
from torch.utils.data import DataLoader # 데이터로더

In [54]:
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  90],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])


In [61]:
dataset = TensorDataset(x_train, y_train)


dataloader = DataLoader(dataset, batch_size=2, shuffle=True)


model = nn.Linear(3, 1)
optimizer = optim.SGD(model.parameters(), lr=1e-5)


num_epochs = 10
for epoch in range(num_epochs + 1):
  for batch_index, samples in enumerate(dataloader):
    x_train, y_train = samples
    pred = model(x_train)
    cost = F.mse_loss(pred, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, num_epochs, batch_index+1, len(dataloader),
        cost.item()))


Epoch    0/10 Batch 1/1 Cost: 15363.887695
Epoch    1/10 Batch 1/1 Cost: 3827.769775
Epoch    2/10 Batch 1/1 Cost: 953.654785
Epoch    3/10 Batch 1/1 Cost: 237.593323
Epoch    4/10 Batch 1/1 Cost: 59.194351
Epoch    5/10 Batch 1/1 Cost: 14.747799
Epoch    6/10 Batch 1/1 Cost: 3.674274
Epoch    7/10 Batch 1/1 Cost: 0.915412
Epoch    8/10 Batch 1/1 Cost: 0.228058
Epoch    9/10 Batch 1/1 Cost: 0.056829
Epoch   10/10 Batch 1/1 Cost: 0.014155


In [62]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred)


훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.7994]], grad_fn=<AddmmBackward0>)


# Custom Dataset

In [63]:
# class CustomDataset(torch.utils.data.Dataset):
#   def __init__(self):
#   데이터셋의 전처리를 해주는 부분

#   def __len__(self):
#   데이터셋의 길이. 즉, 총 샘플의 수를 적어주는 부분

#   def __getitem__(self, idx):
#   데이터셋에서 특정 1개의 샘플을 가져오는 함수

In [64]:
class CustomDataset(torch.utils.data.Dataset):
  def __init__(self):
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  # 총 데이터의 개수를 리턴
  def __len__(self):
    return len(self.x_data)

  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
  def __getitem__(self, idx):
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

In [65]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)


model = torch.nn.Linear(3, 1)
optimizer = optim.SGD(model.parameters(), lr=1e-5)

In [72]:
nb_epochs = 1000
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/1000 Batch 1/3 Cost: 3.652189
Epoch    0/1000 Batch 2/3 Cost: 6.667732
Epoch    0/1000 Batch 3/3 Cost: 10.125944
Epoch    1/1000 Batch 1/3 Cost: 3.825957
Epoch    1/1000 Batch 2/3 Cost: 5.592238
Epoch    1/1000 Batch 3/3 Cost: 3.059990
Epoch    2/1000 Batch 1/3 Cost: 1.643597
Epoch    2/1000 Batch 2/3 Cost: 5.868298
Epoch    2/1000 Batch 3/3 Cost: 7.397660
Epoch    3/1000 Batch 1/3 Cost: 3.501590
Epoch    3/1000 Batch 2/3 Cost: 5.715477
Epoch    3/1000 Batch 3/3 Cost: 6.202787
Epoch    4/1000 Batch 1/3 Cost: 2.735502
Epoch    4/1000 Batch 2/3 Cost: 4.074830
Epoch    4/1000 Batch 3/3 Cost: 8.420942
Epoch    5/1000 Batch 1/3 Cost: 1.798299
Epoch    5/1000 Batch 2/3 Cost: 5.662962
Epoch    5/1000 Batch 3/3 Cost: 7.219950
Epoch    6/1000 Batch 1/3 Cost: 4.495107
Epoch    6/1000 Batch 2/3 Cost: 2.264223
Epoch    6/1000 Batch 3/3 Cost: 8.681159
Epoch    7/1000 Batch 1/3 Cost: 1.851087
Epoch    7/1000 Batch 2/3 Cost: 10.394990
Epoch    7/1000 Batch 3/3 Cost: 4.309856
Epoch    8/100

In [73]:
new_var =  torch.FloatTensor([[73, 80, 75]])
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.6590]], grad_fn=<AddmmBackward0>)
