![](https://wikidocs.net/images/page/31947/%EB%A8%B8%EC%8B%A0_%EB%9F%AC%EB%8B%9D_%EC%9B%8C%ED%81%AC%ED%94%8C%EB%A1%9C%EC%9A%B0.PNG)

수집 : 데이터

점검 및 탐색 : EDA

전처리 및 정제

모델링, 훈련

평가

배포

In [1]:
import torch


t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [2]:
t.dim()

1

In [4]:
t.shape

torch.Size([7])

In [5]:
t.size()

torch.Size([7])

In [6]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])


a = m1 + m2

In [7]:
a

tensor([[5., 5.]])

In [9]:
a.shape

torch.Size([1, 2])

In [10]:
t = [[[0, 1, 2],
      [3, 4, 5]],
     [[6, 7, 8],
      [9, 10, 11]]]
ft = torch.FloatTensor(t)

In [11]:
ft

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [12]:
ft.shape #차원 : 2, 2*3 행렬

torch.Size([2, 2, 3])

In [15]:
ft.dim()

3

In [16]:
ft.squeeze() #1인 차원만 늘려주기

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [17]:
ft.squeeze().shape

torch.Size([2, 2, 3])

In [18]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])


print(torch.cat([x,y])) # 연결

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
